# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JM's blog
email: J.Moudrik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My humble personal blog. Hopefuly, the fact that it is humble in content
    will soon change.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jmoudrik.github.io" # the base hostname & protocol for your site
homepage: "http://j2m.cz/~jm/"
github_username:  jmoudrik
# Build settings
markdown: kramdown
